### ISSUE TITLE
dock-related methods are missing from the index

### ISSUE THREAD

**Issue by zeke** [electron/algolia-indices#16]
- app.dock.downloadFinished(filePath)
- app.dock.hide()
- app.dock.setBadge(text)

https://electronjs.org/docs/api/app#appdockbouncetype-macos

etc...

**Comment by zeke** [comment]
This may help track down the dock methods in the source JSON: https://github.com/electron/electron-api-docs/blob/a19afe27d536d6b7bc3b94db3eaeb0d4eb45e1e9/build.js#L29-L32

**Comment by erickzhao** [comment]
Believe this is done now:

![image](https://user-images.githubusercontent.com/16010076/101670655-4bc0ad80-3a08-11eb-9c91-0a19ed871fd7.png)
