### ISSUE TITLE
ipcMain events are missing from the index

### ISSUE THREAD

**Issue by zeke** [electron/algolia-indices#21]
Several methods exist: https://electronjs.org/docs/api/ipc-main#methods

But where are they?

<img width="785" alt="screen shot 2018-06-21 at 10 02 57 pm" src="https://user-images.githubusercontent.com/2289/41758636-e4f8fc36-759e-11e8-8221-9c5c5f8317d5.png">

**Comment by vhashimotoo** [comment]
Fixed in the squashed commit.
