### ISSUE TITLE
isPackaged not available in search

### ISSUE THREAD

**Issue by schontz** [electron/algolia-indices#25]
Not sure what else from 3.0.0 is missing. If the value isn't found is there a server-side search this can post to?

**Comment by zeke** [comment]
The Electron API data for Electron's website search index comes from the `electron-api.json` file that's published with each release on GitHub. The `isPackaged` property is present in that file for electron@3.0.0, so there's probably something in this repo that is causing this property to be skipped.

**Comment by vhashimotoo** [comment]
Fixed in the squashed commit.
